course:
    name: HFOSS
    desc: The RIT Humanitarian Free/Open Source Software Development Course
    place: RIT
    start: 2016-01-25
    end: 2016-05-13
    blog_start: 2015-02-07
    blog_end: 2015-05-08
    times: Mon,Wed,Fri 9:00AM - 9:50AM
    course: IGME58201.2151
    location: Orange Hall (ORN)-1380
    final: TBD, 6:30PM-7:45pm, ORN-1380
    repo: http://github.com/ritjoe/hfoss
    public_url: http://hfoss-ritigm.rhcloud.com

instructor:
    name: D. Joe Anderson
    email: deejoe@mail.rit.edu
    irc: dzho
    avatar: https://pbs.twimg.com/profile_images/105005326/r-pentonimo.png
    openhub: None
    twitter: deej0e
    office:
        location: 70-3450
        hours: Thursday 3:30-4:00pm
    links:
        blog: None
        linkedin: None
        github: http://github.com/ritjoe
        opensource: None

assistant:
    name: Mike Nolan (Nolski)
    email: me@michael-nolan.com
    irc: Nolski
