course:
    name: HFOSS
    desc: The RIT Humanitarian Free/Open Source Software Development Course
    place: RIT
    start: 2017-01-23
    end: 2017-05-19
    blog_start: 2017-01-29
    blog_end: 2017-05-12
    times: Mon,Wed,Fri 9:00AM - 9:50AM
    course: IGME58201.2165
    location: Orange Hall (ORN)-1375
    final: TBD, 6:30PM-7:45pm, ORN-1375
    repo: https://github.com/ritjoe/hfoss
    public_url: https://hfoss-ritjoe.rhcloud.com/

instructor:
    name: D. Joe Anderson
    email: deejoe@mail.rit.edu
    irc: dzho
    avatar: https://pbs.twimg.com/profile_images/105005326/r-pentonimo.png
    openhub: None
    twitter: deej0e
    office:
        location: GOL-2500
        hours: Wednesday 4:00-5:00pm
    links:
        blog: http://deejoe.etrumeus.com/update
        linkedin: None
        github: https://github.com/ritjoe
        opensource: None

assistant:
    name: None
    email: None
    irc: None
