course:
    name: HFOSS
    desc: The RIT Humanitarian Free/Open Source Software Development Course
    place: RIT
    start: 2015-08-25
    end: 2015-12-10
    blog_start: 2015-09-08
    blog_end: 2015-12-20
    times: Tue & Thu 6:30PM - 7:45PM
    course: IGME58201.2151
    location: Orange Hall (ORN)-1380
    final: TBD, 6:30PM-7:45pm, ORN-1380
    repo: http://github.com/ritjoe/hfoss
    public_url: http://hfoss-ritigm.rhcloud.com

instructor:
    name: D. Joe Anderson
    email: deejoe@mail.rit.edu
    irc: dzho
    avatar: None
    openhub: None
    twitter: deej0e
    office:
        location: 70-2500
        hours: Tuesday, Thursday, 5:45-6:15pm
    links:
        blog: None
        linkedin: None
        github: http://github.com/ritjoe
        opensource: None

assistant:
    name: Matt Soucy (msoucy)
    email: msoucy@csh.rit.edu
    irc: msoucy

