course:
    name: HFOSS
    desc: The RIT Humanitarian Free/Open Source Software Development Course
    place: RIT
    start: 2016-08-23
    end: 2016-12-15
    blog_start: 2016-08-30
    blog_end: 2016-12-08
    times: Tue,Thu 9:30AM - 10:45AM
    course: IGME58201.2161
    location: Orange Hall (ORN)-1380
    final: TBD, 6:30PM-7:45pm, ORN-1380
    repo: https://github.com/ritjoe/hfoss
    public_url: https://hfoss16f-ritjoe.rhcloud.com/

instructor:
    name: D. Joe Anderson
    email: deejoe@mail.rit.edu
    irc: dzho
    avatar: https://pbs.twimg.com/profile_images/105005326/r-pentonimo.png
    openhub: None
    twitter: deej0e
    office:
        location: 70-2500
        hours: Wednesday 4:00-5:00pm
    links:
        blog: http://deejoe.etrumeus.com/update
        linkedin: None
        github: https://github.com/ritjoe
        opensource: None

assistant:
    name: Justin W. Flory (jflory7)
    email: me@justinwflory.com
    irc: jflory7
